### ISSUE TITLE
opensource backend server

### ISSUE THREAD

**Issue by gringofe** [swdotcom/swdc-intellij#19]
##### SUMMARY

```paste below
In addition to this seemingly great plugin,
you should also provide the backend server source code so people can 
a) independently verify the data is neither shared nor analyzed and 
b) selfhost the server so they can choose how their data is stored
```

##### ISSUE TYPE
- Feature Request

**Comment by brettmstevens7** [comment]
@gringofe thanks for the feature request. Regarding your first point, we will never share your individually identifiable data with anyone, but in the future will allow teams to see their anonymized data. We will support a developer API in the future so you can analyze your own data and will take into consideration your idea for a local server.
