### ISSUE TITLE
cant login on Linux

### ISSUE THREAD

**Issue by bigpodgurc** [swdotcom/swdc-intellij#2]
Cant login on linux with all programs i use
(vscode atom idea pycharm) it pushes me to the page and i login and thats it

**Comment by andrewhli** [comment]
Thanks for letting us know! Right now, we don't 100% support Linux. We're looking to add support later in the month, and I'll be sure to let you know.

**Comment by brettmstevens7** [comment]
@bigpodgurc this is also now fixed for IntelliJ on Linux - the latest version in the marketplace is now v1.87.
