### ISSUE TITLE
Icon in status bar is eye-catching (change color to gray?)

### ISSUE THREAD

**Issue by dima74** [swdotcom/swdc-intellij#21]
##### SUMMARY
Change color of icon in status bar to gray, in order to make it less eye-catching

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION
Icon in status bar has bright blue color. It is cool, but thus unfortunately icon is very eye-catching, which I personally don't like. Could you please add option to make this icon gray (or maybe make it gray by default)?

![image](https://user-images.githubusercontent.com/6505554/77483487-4b13c700-6e39-11ea-8774-fda7149c5b3f.png)

Other icons in status bar tend to be gray:
* cloud sync icon in status bar
* project, structure, favorites icons for tabs in left toolbar

**Comment by brettmstevens7** [comment]
@dima74 thanks for the suggestion and completely agree. The next release will update the icons to be grey:

![icons-update](https://user-images.githubusercontent.com/27828739/78160048-41b9ca00-73f8-11ea-9851-e86dc854c89a.png)

**Comment by dima74** [comment]
@brettmstevens7 thank you!
