### ISSUE TITLE
CPU usage is too high

### ISSUE THREAD

**Issue by AprilViolet** [swdotcom/swdc-intellij#23]
**Describe the bug**
```
CPU usage is too high.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**
1. Open idea Activity Monitor

**ACTUAL RESULTS**
```
The CPU usage has been too high during my code writing. This is not the case in the previous versions, I only recently discovered
```

**Screenshots**
![image](https://user-images.githubusercontent.com/40155496/78095152-de846380-7408-11ea-9aee-b3ec799b7446.png)
**Desktop (please complete the following information):**
 - OS: Windows 1909
 - Plugin version Code Time v1.0.7

**Thanks for your answer**

**Comment by xavluiz** [comment]
Thank you for the update. We've been looking into this issue and have a fix. I apologize about the issue. Version 1.0.10 has been pushed to the marketplace but looks like it's currently not available. I will update this issue when that version is available. Thank you again.

**Comment by AprilViolet** [comment]
Thanks for your reply, I see the new version is waiting for review in the plugin center of idea.

**Comment by xavluiz** [comment]
I've sent a request to the JetBrains plugin admin about the timeline for approval of the new version. Thank you again for your patience.
