### ISSUE TITLE
Malformed report (bad characters)

### ISSUE THREAD

**Issue by gaborando** [swdotcom/swdc-intellij#5]
Platform: Intellij Idea, PhpStorm
O.S: Windows 10

The CodeTime Dashboard generate a malformed file:
[CodeTime.txt](https://github.com/swdotcom/swdc-intellij/files/3059467/CodeTime.txt)

In the same machine and project works on VsCode

**Comment by brettmstevens7** [comment]
Thanks @gaborando - we're working now on improving formatting on Linux and Windows.

**Comment by brettmstevens7** [comment]
Hi @gaborando - this was an issue with file encoding that should now be fixed in the latest version (pending marketplace approval).
